site:
  title: Package Distribution Documentation
  url: https://package-dist.github.io/docs
  start_page: docs::index.adoc

content:
  sources:
  - url: .
    branches: HEAD
    start_path: docs

ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true

output:
  dir: ./public
